version: '3'
services:
  server_flask:
    build: ./server
    volumes:
      - ./server:/user/src/server
    ports:
      - 5000:5000
  client_nginx_vue:
    build: ./client
    volumes:
      - ./client:/user/src/client
    ports:
      - 80:80
      - 8080:8080
  db_mysql:
    build: ./db
    volumes:
      - ./db/:/user/src/db
    ports:
      - 3306:3306
