version: '3.3'
services:
  python:
    container_name: server_python
    ports:
        - '5000:5000'
    image: python
  nodejs:
    container_name: client_nodejs
    ports:
        - '8080:8080'
    image: node
  mysql:
    container_name: db_mysql
    ports:
        - '3306:3306'
    environment:
        - MYSQL_ROOT_PASSWORD=codeup
    image: mysql
