version: "3.8"
services:
  kennely_mysql:
    image: mysql:latest
    container_name: kennely_mysql_db
    build: ./
    environment:
      - MYSQL_ROOT_PASSWORD=petmeplz
    ports: 
      - 3307:3306
    restart: unless-stopped
