version: "3.8"
services:
  pet_mysql:
    image: mysql:latest
    container_name: pet_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=petmeplz
    ports: 
      - 3307:3306
    restart: unless-stopped
